server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Alguefer/car-rental-system.git
          clone-on-start: true
        default-label: main
